import { createContext, useContext, useState, type ReactNode } from "react";

export type Lang = "en" | "zh";

// ── All UI strings ────────────────────────────────────────────────────────────
const T = {
  en: {
    appName:        "FinAI",
    tagline:        "Real-time market data · AI-powered analysis",
    newChat:        "New Chat",
    chat:           "Chat",
    saved:          "Saved",
    signOut:        "Sign out",
    welcome:        'Welcome to FinAI! Ask me about stocks, trends, or financial concepts. Try: "What is the price of AAPL?", "Why did TSLA go up?", or "Explain NVDA\'s P/E ratio".',
    inputPlaceholder: "Ask about any stock...",
    error:          "Error",
    noSaved:        "No saved queries yet.",
    noSavedHint:    "Click the bookmark icon on any response.",
    history:        "History",
    noHistory:      "No past conversations.",
    noHistoryHint:  "Start chatting to build your history.",
    turns:          "turns",
    login:          "Sign in",
    register:       "Create account",
    email:          "Email",
    password:       "Password",
    displayName:    "Your name",
    loginWithGoogle:"Continue with Google",
    orEmail:        "or sign in with email",
    switchToRegister: "Don't have an account? Sign up",
    switchToLogin:  "Already have an account? Sign in",
    saving:         "Saved to cloud",
    keyMetrics:     "Key Metrics",
    priceChart:     "Price Chart",
    recentNews:     "Recent News",
    confidence:     "Confidence",
    sources:        "Sources",
    marketSummary:  "Market Summary",
    analysis:       "Analysis",
    answer:         "Answer",
    generatedByAI:  "Generated by AI",
    signalQuality:  "Signal quality",
    noChartData:    "Not enough data for",
    view:           "view",
    day1Change:     "1D Change",
    day5Change:     "5D Change",
    currentPrice:   "Current Price",
    high52w:        "52W High",
    low52w:         "52W Low",
    pe:             "P/E (TTM)",
    eps:            "EPS",
    beta:           "Beta",
    marketCap:      "Market Cap",
    avgVolume:      "10-day avg volume",
    shares:         "M shares",
  },
  zh: {
    appName:        "FinAI",
    tagline:        "实时行情 · AI 驱动分析",
    newChat:        "新对话",
    chat:           "对话",
    saved:          "收藏",
    signOut:        "退出登录",
    welcome:        '欢迎使用 FinAI！请询问任何股票问题，例如："AAPL 现在价格多少？"、"TSLA 为什么上涨？"或"解释 NVDA 的市盈率"。',
    inputPlaceholder: "询问任何股票...",
    error:          "错误",
    noSaved:        "暂无收藏。",
    noSavedHint:    "点击任意回复上的书签图标即可收藏。",
    history:        "历史",
    noHistory:      "暂无历史对话。",
    noHistoryHint:  "开始聊天以建立历史记录。",
    turns:          "条",
    login:          "登录",
    register:       "创建账号",
    email:          "邮箱",
    password:       "密码",
    displayName:    "您的姓名",
    loginWithGoogle:"使用 Google 继续",
    orEmail:        "或使用邮箱登录",
    switchToRegister: "没有账号？立即注册",
    switchToLogin:  "已有账号？立即登录",
    saving:         "已保存至云端",
    keyMetrics:     "关键指标",
    priceChart:     "价格走势",
    recentNews:     "最新新闻",
    confidence:     "置信度",
    sources:        "数据来源",
    marketSummary:  "行情摘要",
    analysis:       "分析",
    answer:         "答复",
    generatedByAI:  "AI 生成",
    signalQuality:  "信号质量",
    noChartData:    "数据不足，无法展示",
    view:           "视图",
    day1Change:     "日涨跌",
    day5Change:     "5日涨跌",
    currentPrice:   "现价",
    high52w:        "52周高点",
    low52w:         "52周低点",
    pe:             "市盈率(TTM)",
    eps:            "每股收益",
    beta:           "贝塔系数",
    marketCap:      "市值",
    avgVolume:      "10日均量",
    shares:         "百万股",
  },
} as const;

export type Translations = { [K in keyof typeof T.en]: string };

interface LangContextValue {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: Translations;
}

const LangContext = createContext<LangContextValue | null>(null);

export function LangProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>(() => {
    try {
      return (localStorage.getItem("finai_lang") as Lang) || "en";
    } catch { return "en"; }
  });

  const setLang = (l: Lang) => {
    setLangState(l);
    try { localStorage.setItem("finai_lang", l); } catch { /* ignore */ }
  };

  return (
    <LangContext.Provider value={{ lang, setLang, t: T[lang] as Translations }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  const ctx = useContext(LangContext);
  if (!ctx) throw new Error("useLang must be used inside <LangProvider>");
  return ctx;
}
